import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import { Button } from '@mui/material'
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
        <div id='headContainer'>  {/* container for heading and button to act as group */}
          <h1>Detrator FE Developer Assignment</h1>
        <Button onClick={()=>router.push("/posts")} variant='contained' endIcon={<ChevronRightIcon/>}>Posts</Button>
        </div>
      </main>
    </>
  )
}
